### PR TITLE
Fix Kudo buttons to work with Strava React rewrite (by @ThomasMldr)

### PR DESCRIPTION
**Pull request by ThomasMldr**
the simple js selector from before is gone, the arrive.js can't properly observe the data that's being loaded with react and has data-attributes that are being set after load (not even with fireOnAttributesModification apparently).
checking can_kudo in the data-react-props ensures that we check if a button needs to be clicked or not (for example not click your own kudo button which opens a popup)

### CODE REVIEW

**Comment by Strajk** [comment]
looks nice :kudos: :))

will check more & test later today or tomorrow 🏃

**Comment by skorozsi** [comment]
@ThomasMldr thanks for the fix! I overwrote my local extension source files with your changes and it works for me! :)

**Comment by skorozsi** [comment]
> @ThomasMldr thanks for the fix! I overwrote my local extension source files with your changes and it works for me! :)

Unfortunately chrome disabled the extension... "This extension may have been corrupted." :(  Probably I should install the extension as unpacked until it will be released officially.

**Comment by Strajk** [comment]
First of all, sorry for being late with code review - busy busy at work :))

I'm just checking the Strava React rewrite, and they seem to have a bug in Kudos button title text.
If they would fix it, adjusting the extension to work properly would be trivial 🤯

2021-08-10 21 29 27@2x

But with no proper CSS selector of kudoable buttons as of now, there probably is no other way than hardcore checking data-react-props as proposed

---

So let's merge this, and check later if Strava fixes the bug so we can simplify the code again :))

**Comment by Strajk** [comment]
btw there's probably more stuff broken with React rewrite 😢 
I've noticed the keyboard navigation does not work anymore (that's what I use the most)

**Comment by ThomasMldr** [comment]
> I'm just checking the Strava React rewrite, and they seem to have a bug in Kudos button title text.
> If they would fix it, adjusting the extension to work properly would be trivial 🤯

Indeed, I see what you mean but I think the Strava website is available in multiple languages, so checking the title text might be more annoying if we want to keep other languages supported ... A class or id like before would be much better of course 😊

**Comment by ThomasMldr** [comment]
> btw there's probably more stuff broken with React rewrite 😢
> I've noticed the keyboard navigation does not work anymore (that's what I use the most)

Hmmm bummer, if I have some time in the next days I'll see if I can take a look too!

**Comment by Strajk** [comment]
> available in multiple languages

yea you are totally right!

I've submitted updated version to Chrome Web Store (would be great to have CD to do that automatically 🙏) 

btw Google is requiring more and more info about extensions, but that's probably a good thing for users :)

image

**Comment by Strajk** [comment]
>  I'll see if I can take a look too!

Would be great! But don't forget to run/bike/swim too – so you have a lot of activities for testing :))

**Comment by Strajk** [comment]
ha, i totally forgot that there's CD set up already 😅

Each commit on develop is linted and then released as BETA https://chrome.google.com/webstore/detail/strava-enhancement-suite/oaioodcklbhlefejbglemgjndhckgklf

There are some lint errors from your code (seems like just `'` instead of `"`), so the CD was skipped

https://github.com/Strajk/strava-enhancement-suite/actions/runs/1117822408

But that's no biggie

**Pull request merged**
