### PR TITLE
Remove "standard_google_map" feature

### PR DESCRIPTION
**Pull request by Strajk**
Remove "standard_google_map" feature, as terrain map is no longer on Strava

image

### CODE REVIEW

**Comment by Strajk** [comment]
@lamby btw if you would like any help managing repo, publishing, anything else; it would be a pleasure for me :)

I've just started training for a triathlon, so I'm using Strava pretty extensively 😅

**Comment by lamby** [comment]
@Strajk Would you be interested in taking over the project? I do not use Strava these days..

**Comment by Strajk** [comment]
@lamby if you are ok with it, I definitely would :)

I've already created & contributed to a few browser extensions, but this would definitely be the one with the biggest audience. But I hope I've done my own share of bugs & fuckups in my career to learn to be careful 😅

**Comment by lamby** [comment]
@Strajk Cool. Please open a new issue for this, including your Google account email address. (I might need more, but lets start there...) :+1:

**Comment by Strajk** [comment]
@lamby done https://github.com/lamby/strava-enhancement-suite/issues/92#issue-655573857

**Pull request closed without merging**
