### PR TITLE
keyboard controls after react rewrite

### PR DESCRIPTION
**Pull request by ThomasMldr**

### CODE REVIEW

**Comment by Strajk** [comment]
Epic 👏 👏 👏

**Comment by Strajk** [comment]
If everything (CI) goes well, it should be released to https://chrome.google.com/webstore/detail/strava-enhancement-suite/oaioodcklbhlefejbglemgjndhckgklf soon :)

**Comment by ThomasMldr** [comment]
Hmm CI seems to have failed on "set-env" command somewhere... Not really familiar with these CI builds etc 😅

**Comment by ThomasMldr** [comment]
have noticed that it skips group activities now.. not the worst, but might be worth fixing.. :-)

**Pull request merged**
